### ISSUE TITLE
Merge Navigation and Main apps

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-ui#869]
- [x] Merge Navigation and Main React apps 
- [x] Move navigation to React (deprecate "SET_VIEWS" message) Related #867
- [x] Introduce global state management (e.g. Redux) #910 
- [x] Consider merging "SET_SCOPE", "SET_ENVIRONMENT", and "CHANGE_VIEW" into a single message #867
